version: '2'
services:
  postgres:
    image: postgres:15.1-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./deployment/postgres/data:/var/lib/postgresql/data
  frogress:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: deployment/frogress/Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
