# Generated by Django 4.1 on 2022-08-20 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frog_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="version",
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frog_api.version",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entry",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="frog_api.category",
            ),
            preserve_default=False,
        ),
    ]
