# Generated by Django 4.1 on 2022-08-20 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frog_api", "0002_remove_entry_version_category_entry_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="decompiled_functions",
            new_name="decompiled_chunks",
        ),
        migrations.RenameField(
            model_name="entry",
            old_name="matching_functions",
            new_name="matching_chunks",
        ),
        migrations.RenameField(
            model_name="entry",
            old_name="total_functions",
            new_name="total_chunks",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="other_data",
        ),
    ]
