# Generated by Django 4.1 on 2022-08-24 01:37

from django.db import migrations, models
import frog_api.models


class Migration(migrations.Migration):

    dependencies = [
        ("frog_api", "0005_remove_entry_decompiled_bytes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="auth_key",
            field=models.CharField(default=frog_api.models.gen_auth_key, max_length=10),
        ),
    ]
