# Generated by Django 4.1 on 2022-08-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frog_api", "0007_alter_entry_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="discord",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="repository",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
