# Generated by Django 4.1 on 2022-08-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frog_api", "0008_project_discord_project_repository_project_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="discord",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="repository",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="website",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
