# Generated by Django 4.2.1 on 2023-05-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "frog_api",
            "0001_squashed_0009_alter_project_discord_alter_project_repository_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="frog_api.category"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="discord",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="repository",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("timestamp", "git_hash", "category"), name="unique entry"
            ),
        ),
    ]
